# Generated by Django 5.0.6 on 2026-07-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="bookingstatushistory",
            name="booking_history_booking_idx",
        ),
        migrations.RenameIndex(
            model_name="booking",
            new_name="bookings_tutor_i_4503b5_idx",
            old_name="booking_tutor_start_idx",
        ),
        migrations.RenameIndex(
            model_name="booking",
            new_name="bookings_student_369cea_idx",
            old_name="booking_student_start_idx",
        ),
        migrations.RenameIndex(
            model_name="booking",
            new_name="bookings_status_51373b_idx",
            old_name="booking_status_idx",
        ),
        migrations.RenameIndex(
            model_name="reschedulerequest",
            new_name="booking_res_booking_3f9fd9_idx",
            old_name="reschedule_booking_status_idx",
        ),
        migrations.RenameIndex(
            model_name="sessionattendance",
            new_name="session_att_session_5a361d_idx",
            old_name="attendance_session_user_idx",
        ),
        migrations.AlterField(
            model_name="booking",
            name="location",
            field=models.CharField(
                blank=True, help_text="Required for in-person bookings.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="tutor_notes",
            field=models.TextField(
                blank=True, help_text="Private prep notes, visible only to the tutor."
            ),
        ),
    ]
