# Generated by Django 5.0.6 on 2026-07-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="devicetoken",
            new_name="device_toke_user_id_e99165_idx",
            old_name="device_token_user_active_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_583549_idx",
            old_name="notification_recipient_read_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationdeliverylog",
            new_name="notificatio_notific_65810f_idx",
            old_name="delivery_log_notif_channel_idx",
        ),
        migrations.AlterField(
            model_name="notification",
            name="action_url",
            field=models.CharField(
                blank=True,
                help_text="Frontend route to deep-link to on tap.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Extra structured payload, e.g. related object IDs.",
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="muted_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of NotificationType values the user has opted out of.",
            ),
        ),
    ]
