# Generated by Django 5.0.6 on 2026-07-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutes", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="instituteprofile",
            new_name="institute_p_verific_765ff5_idx",
            old_name="institute_verif_status_idx",
        ),
        migrations.RenameIndex(
            model_name="instituteprofile",
            new_name="institute_p_city_b1f89e_idx",
            old_name="institute_city_idx",
        ),
        migrations.RenameIndex(
            model_name="institutestudentenrollment",
            new_name="institute_s_institu_ce4029_idx",
            old_name="institute_enroll_status_idx",
        ),
        migrations.RenameIndex(
            model_name="institutetutor",
            new_name="institute_t_institu_2268c5_idx",
            old_name="institute_tutor_status_idx",
        ),
        migrations.AlterField(
            model_name="institutetutor",
            name="role_title",
            field=models.CharField(
                blank=True, help_text="e.g. 'Senior Faculty - Physics'", max_length=100
            ),
        ),
    ]
