# Generated by Django 5.0.6 on 2026-07-22 05:11

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.users.models.UserManager()),
            ],
        ),
        migrations.RenameIndex(
            model_name="loginauditlog",
            new_name="login_audit_user_id_1533ac_idx",
            old_name="login_audit_user_event_idx",
        ),
        migrations.RenameIndex(
            model_name="otp",
            new_name="otps_user_id_2340ab_idx",
            old_name="otps_user_purpose_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="users_role_a8f2ba_idx",
            old_name="users_role_active_idx",
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
