# Generated by Django 5.0.6 on 2026-07-22 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parents", "0002_masterdata_vocabulary"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="parentstudentlink",
            new_name="parent_stud_student_7b317e_idx",
            old_name="parent_link_student_status_idx",
        ),
    ]
