# Generated by Django 5.0.6 on 2026-07-22 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_masterdata_vocabulary"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="assignment",
            new_name="assignments_course__5095d8_idx",
            old_name="assignment_course_due_idx",
        ),
        migrations.RenameIndex(
            model_name="assignmentsubmission",
            new_name="assignment__assignm_68808b_idx",
            old_name="submission_assignment_status_idx",
        ),
        migrations.RenameIndex(
            model_name="course",
            new_name="courses_status_21138b_idx",
            old_name="course_status_subject_idx",
        ),
        migrations.RenameIndex(
            model_name="course",
            new_name="courses_tutor_i_93c57e_idx",
            old_name="course_tutor_status_idx",
        ),
        migrations.RenameIndex(
            model_name="courseattendance",
            new_name="course_atte_session_038d79_idx",
            old_name="attendance_session_status_idx",
        ),
        migrations.RenameIndex(
            model_name="courseenrollment",
            new_name="course_enro_course__37db5f_idx",
            old_name="enrollment_course_status_idx",
        ),
        migrations.RenameIndex(
            model_name="coursesession",
            new_name="course_sess_course__e63007_idx",
            old_name="course_session_start_idx",
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(1000)],
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="max_students",
            field=models.PositiveSmallIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=9,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="total_sessions",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
