# Generated by Django 5.0.6 on 2026-07-22 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="coursereview",
            new_name="course_revi_course__996bc0_idx",
            old_name="course_review_course_flag_idx",
        ),
        migrations.RenameIndex(
            model_name="tutorreview",
            new_name="tutor_revie_tutor_i_ffa3ec_idx",
            old_name="tutor_review_tutor_flag_idx",
        ),
    ]
