# Generated by Django 5.0.6 on 2026-07-22 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_masterdata_vocabulary"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="studentprofile",
            new_name="student_pro_grade_l_b455ac_idx",
            old_name="student_grade_level_idx",
        ),
        migrations.RenameIndex(
            model_name="studentprofile",
            new_name="student_pro_city_2437d5_idx",
            old_name="student_city_idx",
        ),
    ]
