# Generated by Django 5.0.6 on 2026-07-22 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="conversation",
            new_name="conversatio_related_0bf8fc_idx",
            old_name="conversation_booking_idx",
        ),
        migrations.RenameIndex(
            model_name="conversation",
            new_name="conversatio_related_aada46_idx",
            old_name="conversation_course_idx",
        ),
        migrations.RenameIndex(
            model_name="conversationparticipant",
            new_name="conversatio_user_id_4a2524_idx",
            old_name="conv_participant_user_idx",
        ),
        migrations.RenameIndex(
            model_name="message",
            new_name="messages_convers_3ebb41_idx",
            old_name="message_conversation_created_idx",
        ),
    ]
