# Generated by Django 5.0.6 on 2026-07-22 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutors", "0002_masterdata_vocabulary"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="availabilityexception",
            new_name="tutor_avail_tutor_i_cc6525_idx",
            old_name="avail_exception_tutor_date_idx",
        ),
        migrations.RenameIndex(
            model_name="subject",
            new_name="subjects_categor_3104ae_idx",
            old_name="subjects_cat_active_idx",
        ),
        migrations.RenameIndex(
            model_name="tutorprofile",
            new_name="tutor_profi_verific_40c62e_idx",
            old_name="tutor_verif_accept_idx",
        ),
        migrations.RenameIndex(
            model_name="tutorprofile",
            new_name="tutor_profi_city_b3cc30_idx",
            old_name="tutor_city_idx",
        ),
        migrations.RenameIndex(
            model_name="tutorprofile",
            new_name="tutor_profi_rating__54087e_idx",
            old_name="tutor_rating_idx",
        ),
        migrations.RenameIndex(
            model_name="verificationdocument",
            new_name="tutor_verif_tutor_i_242282_idx",
            old_name="verif_doc_tutor_status_idx",
        ),
        migrations.RenameIndex(
            model_name="weeklyavailability",
            new_name="tutor_weekl_tutor_i_c6260a_idx",
            old_name="weekly_avail_tutor_day_idx",
        ),
        migrations.AlterField(
            model_name="availabilityexception",
            name="is_available",
            field=models.BooleanField(
                default=False,
                help_text="False = blocked/leave day. True = extra one-off slot.",
            ),
        ),
        migrations.AlterField(
            model_name="subjectcategory",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Icon identifier for frontend (e.g. lucide name).",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="headline",
            field=models.CharField(
                blank=True,
                help_text="e.g. 'IIT Alumnus | Physics & Math Expert'",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="hourly_rate",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="languages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of language codes/names spoken.",
            ),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="travel_radius_km",
            field=models.PositiveSmallIntegerField(
                default=10, help_text="Max travel distance for in-person classes."
            ),
        ),
    ]
