import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("balance", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("is_frozen", models.BooleanField(default=False)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="wallet", to="users.user")),
            ],
            options={"db_table": "wallets"},
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("code", models.CharField(db_index=True, max_length=30, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("discount_type", models.CharField(choices=[("percentage", "Percentage"), ("flat", "Flat Amount")], max_length=15)),
                ("discount_value", models.DecimalField(decimal_places=2, max_digits=8)),
                ("max_discount_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("min_order_amount", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("applicable_to", models.CharField(choices=[("all", "All Purchases"), ("booking", "Bookings Only"), ("course", "Courses Only"), ("subscription", "Subscriptions Only")], default="all", max_length=20)),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("usage_limit_total", models.PositiveIntegerField(blank=True, null=True)),
                ("usage_limit_per_user", models.PositiveSmallIntegerField(default=1)),
                ("times_used", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="coupons_created", to="users.user")),
            ],
            options={"db_table": "coupons"},
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("gateway", models.CharField(choices=[("razorpay", "Razorpay"), ("stripe", "Stripe"), ("wallet", "Wallet Balance")], max_length=20)),
                ("purpose", models.CharField(choices=[("booking", "Booking"), ("course_enrollment", "Course Enrollment"), ("subscription", "Subscription"), ("wallet_topup", "Wallet Top-up")], max_length=30)),
                ("reference_id", models.UUIDField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("discount_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("status", models.CharField(choices=[("created", "Created"), ("pending", "Pending"), ("paid", "Paid"), ("failed", "Failed"), ("refunded", "Refunded"), ("partially_refunded", "Partially Refunded")], db_index=True, default="created", max_length=20)),
                ("gateway_order_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("gateway_payment_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("gateway_signature", models.CharField(blank=True, max_length=512)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("coupon", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payments", to="payments.coupon")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="users.user")),
            ],
            options={"db_table": "payments"},
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("transaction_type", models.CharField(choices=[("credit", "Credit"), ("debit", "Debit")], max_length=10)),
                ("category", models.CharField(choices=[("booking_payout", "Booking Payout"), ("course_payout", "Course Payout"), ("refund", "Refund"), ("referral_bonus", "Referral Bonus"), ("coupon_credit", "Coupon Credit"), ("wallet_topup", "Wallet Top-up"), ("withdrawal", "Withdrawal"), ("manual_adjustment", "Manual Adjustment"), ("subscription_payment", "Subscription Payment")], max_length=30)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("reference_type", models.CharField(blank=True, max_length=50)),
                ("reference_id", models.UUIDField(blank=True, null=True)),
                ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to="payments.wallet")),
            ],
            options={"db_table": "wallet_transactions"},
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("processed", "Processed"), ("failed", "Failed")], default="pending", max_length=20)),
                ("gateway_refund_id", models.CharField(blank=True, max_length=255)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("initiated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="users.user")),
                ("payment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="refunds", to="payments.payment")),
            ],
            options={"db_table": "refunds"},
        ),
        migrations.CreateModel(
            name="CouponRedemption",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("discount_applied", models.DecimalField(decimal_places=2, max_digits=8)),
                ("coupon", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="redemptions", to="payments.coupon")),
                ("payment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="payments.payment")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="coupon_redemptions", to="users.user")),
            ],
            options={"db_table": "coupon_redemptions"},
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("target_role", models.CharField(choices=[("student", "Student"), ("tutor", "Tutor"), ("institute_admin", "Institute")], max_length=20)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("billing_interval", models.CharField(choices=[("monthly", "Monthly"), ("quarterly", "Quarterly"), ("yearly", "Yearly")], default="monthly", max_length=15)),
                ("features", models.JSONField(blank=True, default=list)),
                ("max_bookings_per_month", models.PositiveIntegerField(blank=True, null=True)),
                ("commission_discount_percent", models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"db_table": "subscription_plans"},
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("status", models.CharField(choices=[("pending_payment", "Pending Payment"), ("active", "Active"), ("cancelled", "Cancelled"), ("expired", "Expired"), ("past_due", "Past Due")], default="pending_payment", max_length=20)),
                ("started_at", models.DateTimeField()),
                ("current_period_end", models.DateTimeField()),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("gateway_subscription_id", models.CharField(blank=True, max_length=255)),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subscribers", to="payments.subscriptionplan")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subscriptions", to="users.user")),
            ],
            options={"db_table": "user_subscriptions"},
        ),
        migrations.CreateModel(
            name="ReferralReward",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("credited", "Credited")], default="pending", max_length=20)),
                ("credited_at", models.DateTimeField(blank=True, null=True)),
                ("referred_user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="referral_reward_source", to="users.user")),
                ("referrer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="referral_rewards_earned", to="users.user")),
                ("triggering_payment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="payments.payment")),
            ],
            options={"db_table": "referral_rewards"},
        ),
        migrations.AddConstraint(
            model_name="referralreward",
            constraint=models.UniqueConstraint(fields=("referrer", "referred_user"), name="unique_referral_reward"),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(fields=["code", "is_active"], name="coupon_code_active_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["user", "status"], name="payment_user_status_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["purpose", "reference_id"], name="payment_purpose_ref_idx"),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(fields=["wallet", "created_at"], name="wallet_txn_wallet_created_idx"),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(fields=["reference_type", "reference_id"], name="wallet_txn_reference_idx"),
        ),
        migrations.AddIndex(
            model_name="couponredemption",
            index=models.Index(fields=["coupon", "user"], name="coupon_redemption_user_idx"),
        ),
        migrations.AddIndex(
            model_name="usersubscription",
            index=models.Index(fields=["user", "status"], name="subscription_user_status_idx"),
        ),
    ]
