# Generated by Django 5.0.6 on 2026-07-22 05:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="coupon",
            new_name="coupons_code_e67bf2_idx",
            old_name="coupon_code_active_idx",
        ),
        migrations.RenameIndex(
            model_name="couponredemption",
            new_name="coupon_rede_coupon__1d3d2e_idx",
            old_name="coupon_redemption_user_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_user_id_1b771c_idx",
            old_name="payment_user_status_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_purpose_9e774d_idx",
            old_name="payment_purpose_ref_idx",
        ),
        migrations.RenameIndex(
            model_name="usersubscription",
            new_name="user_subscr_user_id_c57286_idx",
            old_name="subscription_user_status_idx",
        ),
        migrations.RenameIndex(
            model_name="wallettransaction",
            new_name="wallet_tran_wallet__aa27da_idx",
            old_name="wallet_txn_wallet_created_idx",
        ),
        migrations.RenameIndex(
            model_name="wallettransaction",
            new_name="wallet_tran_referen_f20c6c_idx",
            old_name="wallet_txn_reference_idx",
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="usage_limit_total",
            field=models.PositiveIntegerField(
                blank=True, help_text="Blank = unlimited.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="reference_id",
            field=models.UUIDField(
                help_text="ID of the Booking / CourseEnrollment / UserSubscription being paid for."
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="initiated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="max_bookings_per_month",
            field=models.PositiveIntegerField(
                blank=True, help_text="Blank = unlimited.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="is_frozen",
            field=models.BooleanField(
                default=False,
                help_text="Frozen wallets cannot be debited or withdrawn from.",
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="reference_type",
            field=models.CharField(
                blank=True,
                help_text="e.g. 'booking', 'course_enrollment', 'payment' — lightweight polymorphic link.",
                max_length=50,
            ),
        ),
    ]
